categories:
    path:     /
    defaults: { _controller: "AppBundle:Categories:index" }

categories_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Categories:show" }

categories_new:
    path:     /new
    defaults: { _controller: "AppBundle:Categories:new" }

categories_create:
    path:     /create
    defaults: { _controller: "AppBundle:Categories:create" }
    methods:  POST

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Categories:edit" }

categories_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Categories:update" }
    methods:  [POST, PUT]

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Categories:delete" }
    methods:  [GET, POST, DELETE]
