content:
    path:     /
    defaults: { _controller: "AppBundle:Content:index" }

content_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Content:show" }

content_new:
    path:     /new
    defaults: { _controller: "AppBundle:Content:new" }

content_create:
    path:     /create
    defaults: { _controller: "AppBundle:Content:create" }
    methods:  POST

content_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Content:edit" }

content_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Content:update" }
    methods:  [POST, PUT]

content_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Content:delete" }
    methods:  [GET, POST, DELETE]
